services:
  - type: web
    name: shl-assessment-recommender
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    envVars:
      - key: FLASK_ENV
        value: production
